### ISSUE TITLE
MySQL connectior isn't working

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#15]
I've created mysql database `linstor` and gave access to the `linstor` user.

here is my `database.cfg` file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
  <comment>LinStor database configuration</comment>
  <entry key="user">linstor</entry>
  <entry key="password">papae8eihohf3Rie</entry>
  <entry key="connection-url">jdbc:mysql://linstordb-pxc/linstor</entry>
</properties>
```

Here is output of my controller:
```
LINSTOR, Module Controller
Version:            0.6.4 (464f6e5b198002e0d82122d84c27e1b06ec0400c)
Build time:         2018-09-14T10:20:12+00:00
Java Version:       1.8
Java VM:            Oracle Corporation, Version 25.181-b13
Operating system:   Linux, Version 4.15.18-3-pve
Environment:        amd64, 8 processors, 7131 MiB memory reserved for allocations

System components initialization in progress

12:01:09.059 [main] INFO  LINSTOR/Controller - Log directory set to: '/logs'
12:01:09.061 [Main] INFO  LINSTOR/Controller - Loading API classes started.
12:01:09.270 [Main] INFO  LINSTOR/Controller - API classes loading finished: 209ms
12:01:09.270 [Main] INFO  LINSTOR/Controller - Dependency injection started.
12:01:09.850 [Main] INFO  LINSTOR/Controller - Dependency injection finished: 580ms
12:01:09.932 [Main] INFO  LINSTOR/Controller - Initializing the database connection pool
12:01:10.016 [Main] INFO  org.flywaydb.core.internal.util.VersionPrinter - Flyway Community Edition 5.0.7 by Boxfuse
Fri Sep 21 12:01:10 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12:01:10.271 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:mysql://linstordb-pxc/linstor (MySQL 5.7)
12:01:10.309 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:11.325 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:12.335 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:13.345 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:14.355 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:15.363 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:16.373 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:17.382 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:18.391 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:19.400 [Main] INFO  org.flywaydb.core.internal.command.DbSchemas - Creating schema `LINSTOR` ...
12:01:19.413 [Main] ERROR LINSTOR/Controller - 
Unable to create schema `LINSTOR`
---------------------------------
SQL State  : 42000
Error Code : 1044
Message    : Access denied for user 'linstor'@'%' to database 'LINSTOR'
 [Report number 5BA4DD84-00000-000000]

12:01:19.414 [Thread-1] INFO  LINSTOR/Controller - Shutdown in progress
12:01:19.414 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'DatabaseService' of type DatabaseService
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'DatabaseService' to complete shutdown
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TaskScheduleService' to complete shutdown
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TimerEventService' of type TimerEventService
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TimerEventService' to complete shutdown
12:01:19.415 [Thread-1] INFO  LINSTOR/Controller - Shutdown complete
```

trace log and error report in attachment:
* [trace.log](https://github.com/LINBIT/linstor-server/files/2405291/trace.log)
* [ErrorReport-5BA4E053-00000-000000.log](https://github.com/LINBIT/linstor-server/files/2405292/ErrorReport-5BA4E053-00000-000000.log)

**Comment by ghernadi** [comment]
`Unable to create schema `LINSTOR``
looks like your `linstor` mysql user is not allowed to create a new schema? can you try creating that schema manually?

**Comment by kvaps** [comment]
Hi @ghernadi , I already have `linstor` database and user `linstor` have full access rights there, should I also create `LINSTOR` database?

Presume that database and schema is the same things:
https://stackoverflow.com/a/1219723/2931267

**Comment by ghernadi** [comment]
From https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html
```
Consequently, the case sensitivity of the underlying operating system plays a part
in the case sensitivity of database, table, and trigger names. This means such 
names are not case-sensitive in Windows, but are case-sensitive in most varieties 
of Unix.
```
So yes, please delete and re-add the `LINSTOR` database.

**Comment by kvaps** [comment]
> So yes, please delete and re-add the LINSTOR database.
If I do that, linstor-controller says me that can't get access to that database.

I've done the next thing:
I've added `lower_case_table_names = 1` into `my.conf` config

Now I have the new problem:

[trace.1.log](https://github.com/LINBIT/linstor-server/files/2405477/trace.1.log)
[ErrorReport-5BA4EDFB-00000-000000.log](https://github.com/LINBIT/linstor-server/files/2405474/ErrorReport-5BA4EDFB-00000-000000.log)

```
13:11:24.843 [Main] ERROR org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate - Unable to release MySQL named lock: Flyway--556552316
java.sql.SQLException: Percona-XtraDB-Cluster prohibits use of RELEASE_LOCK with pxc_strict_mode = ENFORCING
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:392)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
        at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:197)
        at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.execute(JdbcTemplate.java:246)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:73)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:78)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:148)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:176)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:145)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1206)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1168)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
        at com.linbit.linstor.dbcp.DbConnectionPool.migrate(DbConnectionPool.java:182)
        at com.linbit.linstor.dbcp.DbConnectionPoolInitializer.initialize(DbConnectionPoolInitializer.java:66)
        at com.linbit.linstor.core.Controller.start(Controller.java:192)
        at com.linbit.linstor.core.Controller.main(Controller.java:379)
13:11:24.852 [Main] ERROR LINSTOR/Controller -
Unable to acquire MySQL named lock: Flyway--556552316
-----------------------------------------------------
SQL State  : HY000
Error Code : 1105
Message    : Percona-XtraDB-Cluster prohibits use of GET_LOCK with pxc_strict_mode = ENFORCING
 [Report number 5BA4EDFB-00000-000000]
```

Does it meaning that linstor not support galera cluster?

**Comment by kvaps** [comment]
Probably it is upstream bug of flyway
https://github.com/flyway/flyway/issues/1740

**Comment by kvaps** [comment]
About case sensitivity of database name I think it is another bug, probably linstor uses both names in his sql syntax `linstor` and `LINSTOR`, you should use only one, or provide information that mysql database requires additional setting `lower_case_table_names = 1`.

**Comment by ghernadi** [comment]
Thank you for reporting the issue. 
It looks like the Flyway framework is indeed currently incompatible with Percona-XtraDB-Cluster https://github.com/flyway/flyway/issues/1556
One of the comments of the mentioned Flyway issue also states that this bug will be addressed in 5.2.0 which is not released yet. As soon as this version is released, we can check if we can upgrade safely to it. 
In case we forget about this issue until then, feel free to remind us. I'm also leaving this issue open, hoping it helps us remember :)

**Comment by ghernadi** [comment]
> About case sensitivity of database name I think it is another bug, probably linstor uses both names in his sql syntax `linstor` and `LINSTOR`, you should use only one, or provide information that mysql database requires additional setting `lower_case_table_names = 1` for make it working with linstor.

I will look into this

**Comment by ghernadi** [comment]
As far as I can see the actual SQL-statements don't have any "LINSTOR" or "linstor" prefix at all for specifying the schema or database. Instead we are calling `Connection#setSchema(String)` on literally every database connection opened by linstor with the constant of "LINSTOR". When flyway migrates, we also configure it to use the same schema. 

If you find an issue reporting that we try accessing a lower- or mixed-case table name or field name, please let us know, that is definitely a bug and should be replaced by a upper-case constant.

**Comment by kvaps** [comment]
Well, if you replace `<entry key="connection-url">jdbc:mysql://linstordb-pxc/linstor</entry>` to `<entry key="connection-url">jdbc:mysql://linstordb-pxc/LINSTOR</entry>` it will differently not work.

So probably url in config should be lower-case but mysql database should be created in upper-case - that's little confuses you know :)

For now I have no much time for testing that, I've already installed linstor with postgresql cluster.
Thanks for info

**Comment by raltnoeder** [comment]
I am not entirely sure whether or not my information is correct, but if it is, then MariaDB is currently supported while MySQL is not, due to differences in the data types supported by those databases.

The following databases should currently work with LINSTOR:

- H2 (Integrated DB)
- Apache Derby
- PostgreSQL
- DB2 LUW

Databases that will probably currently **not** work:

- Sybase/ASE
- Oracle
- DB2 i
- DB2 z
- Informix
- MySQL

We are working on improving our SQL so that it would work with most of those databases as well in the future.

**Comment by kvaps** [comment]
@raltnoeder thanks for your comment, but I think this is not problem in difference between MySQL and MariaDB, the problem in some MySQL engines.
For example Galera's XtraDB engine isn't working for now due flyway#1740, but presume classic MySQL with master-slave replication will work without any problem.

with `lower_case_table_names = 1` enabled of course

**Comment by kvaps** [comment]
Hi @ghernadi, unforunately XtraDB still not working:

```
LINSTOR, Module Controller
Version:            0.6.5 (d1bd204b9d673f9938226f8c18853e8aae8dd00c)
Build time:         2018-10-02T07:10:01+00:00
Java Version:       1.8
Java VM:            Oracle Corporation, Version 25.181-b13
Operating system:   Linux, Version 4.15.18-7-pve
Environment:        amd64, 8 processors, 7132 MiB memory reserved for allocations

System components initialization in progress

12:48:32.601 [main] INFO  LINSTOR/Controller - Log directory set to: '/logs'
12:48:32.602 [Main] INFO  LINSTOR/Controller - Loading API classes started.
12:48:32.784 [Main] INFO  LINSTOR/Controller - API classes loading finished: 182ms
12:48:32.784 [Main] INFO  LINSTOR/Controller - Dependency injection started.
12:48:33.393 [Main] INFO  LINSTOR/Controller - Dependency injection finished: 609ms
12:48:33.475 [Main] INFO  LINSTOR/Controller - Initializing the database connection pool
12:48:33.560 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.0 by Boxfuse
Wed Oct 24 12:48:43 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12:48:43.822 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:mysql://linstordb2-pxc/LINSTOR (MySQL 5.7)
12:48:43.868 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 8 migrations (execution time 00:00.011s)
Wed Oct 24 12:48:53 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
12:48:53.902 [Main] INFO  org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table: `LINSTOR`.`FLYWAY_SCHEMA_HISTORY`
12:48:53.927 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema `LINSTOR`: << Empty Schema >>
12:48:53.927 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema `LINSTOR` may not be reproducible.
12:48:53.928 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.03.27.14.01 - Initialize the database
Error: SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
12:48:53.943 [Main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema `LINSTOR` to version 2018.03.27.14.01 - Initialize the database failed! Please restore backups and roll back database and code!
12:48:53.960 [Main] ERROR LINSTOR/Controller - SQL State  : HY000
Error Code : 1105
Message    : Percona-XtraDB-Cluster doesn't recommend using SERIALIZABLE isolation with pxc_strict_mode = ENFORCING
 [Report number 5BD06A20-00000-000000]

12:48:53.961 [Thread-1] INFO  LINSTOR/Controller - Shutdown in progress
12:48:53.961 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'DatabaseService' of type DatabaseService
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'DatabaseService' to complete shutdown
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TaskScheduleService' to complete shutdown
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TimerEventService' of type TimerEventService
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TimerEventService' to complete shutdown
12:48:53.963 [Thread-1] INFO  LINSTOR/Controller - Shutdown complete
```

[ErrorReport-5BD06A20-00000-000000.log](https://github.com/LINBIT/linstor-server/files/2510525/ErrorReport-5BD06A20-00000-000000.log)

**Comment by kvaps** [comment]
**UPD:** if I do:

```
SET GLOBAL pxc_strict_mode=PERMISSIVE;
```
on each instance, it's still not working:

```
LINSTOR, Module Controller
Version:            0.6.5 (d1bd204b9d673f9938226f8c18853e8aae8dd00c)
Build time:         2018-10-02T07:10:01+00:00
Java Version:       1.8
Java VM:            Oracle Corporation, Version 25.181-b13
Operating system:   Linux, Version 4.15.18-7-pve
Environment:        amd64, 8 processors, 7132 MiB memory reserved for allocations

System components initialization in progress

13:12:25.320 [main] INFO  LINSTOR/Controller - Log directory set to: '/logs'
13:12:25.321 [Main] INFO  LINSTOR/Controller - Loading API classes started.
13:12:25.525 [Main] INFO  LINSTOR/Controller - API classes loading finished: 204ms
13:12:25.526 [Main] INFO  LINSTOR/Controller - Dependency injection started.
13:12:26.202 [Main] INFO  LINSTOR/Controller - Dependency injection finished: 676ms
13:12:26.302 [Main] INFO  LINSTOR/Controller - Initializing the database connection pool
13:12:26.389 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 5.2.0 by Boxfuse
Wed Oct 24 13:12:26 UTC 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
13:12:26.649 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:mysql://linstordb2-pxc/LINSTOR (MySQL 5.7)
13:12:26.692 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 8 migrations (execution time 00:00.010s)
13:12:26.700 [Main] INFO  org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table: `LINSTOR`.`FLYWAY_SCHEMA_HISTORY`
13:12:26.726 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema `LINSTOR`: << Empty Schema >>
13:12:26.726 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema `LINSTOR` may not be reproducible.
13:12:26.727 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.03.27.14.01 - Initialize the database
13:12:26.892 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.04.16.12.30 - Merging Satellite_Connections into Nodes_Net_Interfaces
13:12:26.913 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.05.23.16.53 - Add snapshot definitions
13:12:26.923 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.05.30.15.55 - Add snapshots and snapshot volume definitions
13:12:26.941 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.06.08.14.45 - Add size to snapshot volume definition
13:12:26.952 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.06.13.10.26 - Add flags to snapshot volume definition
13:12:26.965 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema `LINSTOR` to version 2018.08.20.17.00 - Extending StorPool table with FreeSpaceMgr
13:12:26.967 [Main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema `LINSTOR` to version 2018.08.20.17.00 - Extending StorPool table with FreeSpaceMgr failed! Please restore backups and roll back database and code!
13:12:26.979 [Main] ERROR LINSTOR/Controller - SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('SYSTEM:')' at line 1
 [Report number 5BD06FB9-00000-000000]

13:12:26.980 [Thread-1] INFO  LINSTOR/Controller - Shutdown in progress
13:12:26.980 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'DatabaseService' of type DatabaseService
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'DatabaseService' to complete shutdown
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TaskScheduleService' to complete shutdown
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Shutting down service instance 'TimerEventService' of type TimerEventService
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Waiting for service instance 'TimerEventService' to complete shutdown
13:12:26.981 [Thread-1] INFO  LINSTOR/Controller - Shutdown complete
```
[ErrorReport-5BD06FB9-00000-000000.log](https://github.com/LINBIT/linstor-server/files/2510611/ErrorReport-5BD06FB9-00000-000000.log)

**Comment by raltnoeder** [comment]
There are currently a couple of fixes regarding ANSI compliance of our SQL in the queue, so those will be in one of the next view releases in LINSTOR.
However, I doubt that those will implicitly also fix issues with MySQL, since there appear to be some more complex issues with MySQL in particular, such as incompatibility with ANSI SQL regarding some operators as well as possibly a lack of support for certain constraints/checks.

As of now, we are currently successfully running recent versions of LINSTOR in our test environment with the following databases:

- H2 1.4 (integrated in the Controller)
- PostgreSQL 9.5
- MariaDB 10.3.10
- IBM DB2 11.1

A column type mismatch with snapshots vs storage pools currently prevents Apache Derby from initializing properly, and it will also cause problems with snapshots on storage pools that have a name that is longer than 32 characters. We are working on fixing this issue.
