### ISSUE TITLE
linstor-controller upgrade from 1.12.0 to 1.12.1 failed - database error

### ISSUE THREAD

**Issue by candlerb** [LINBIT/linstor-server#229]
Ubuntu 18.04, linbit PPA.  The actual upgrade appeared to go fine:

```
root@node1:~# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  linstor-common linstor-controller linstor-satellite
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 37.3 MB of archives.
After this operation, 11.3 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ppa.launchpad.net/linbit/linbit-drbd9-stack/ubuntu bionic/main amd64 linstor-satellite all 1.12.1-1ppa1~bionic1 [655 kB]
Get:2 http://ppa.launchpad.net/linbit/linbit-drbd9-stack/ubuntu bionic/main amd64 linstor-controller all 1.12.1-1ppa1~bionic1 [10.2 MB]
Get:3 http://ppa.launchpad.net/linbit/linbit-drbd9-stack/ubuntu bionic/main amd64 linstor-common all 1.12.1-1ppa1~bionic1 [26.5 MB]
Fetched 37.3 MB in 1s (34.5 MB/s)
(Reading database ... 88629 files and directories currently installed.)
Preparing to unpack .../linstor-satellite_1.12.1-1ppa1~bionic1_all.deb ...
Unpacking linstor-satellite (1.12.1-1ppa1~bionic1) over (1.12.0-1ppa1~bionic1) ...
Preparing to unpack .../linstor-controller_1.12.1-1ppa1~bionic1_all.deb ...
Unpacking linstor-controller (1.12.1-1ppa1~bionic1) over (1.12.0-1ppa1~bionic1) ...
Preparing to unpack .../linstor-common_1.12.1-1ppa1~bionic1_all.deb ...
Unpacking linstor-common (1.12.1-1ppa1~bionic1) over (1.12.0-1ppa1~bionic1) ...
Setting up linstor-common (1.12.1-1ppa1~bionic1) ...
Setting up linstor-satellite (1.12.1-1ppa1~bionic1) ...
Setting up linstor-controller (1.12.1-1ppa1~bionic1) ...
Linstor config toml file already exists, exiting
root@node1:~#
```

linstor-satellite is running, but linstor-controller will not start.

```
root@node1:~# journalctl -eu linstor-controller | cat
...
Apr 30 08:57:29 node1 systemd[1]: Started LINSTOR Controller Service.
Apr 30 08:57:30 node1 Controller[6116]: LINSTOR, Module Controller
Apr 30 08:57:30 node1 Controller[6116]: Version:            1.12.1 (24fcedd9cbebfad42c7a195692e93c68d3ab978b)
Apr 30 08:57:30 node1 Controller[6116]: Build time:         2021-04-30T07:35:24+00:00
Apr 30 08:57:30 node1 Controller[6116]: Java Version:       11
Apr 30 08:57:30 node1 Controller[6116]: Java VM:            Ubuntu, Version 11.0.11+9-Ubuntu-0ubuntu2.18.04
Apr 30 08:57:30 node1 Controller[6116]: Operating system:   Linux, Version 4.15.0-142-generic
Apr 30 08:57:30 node1 Controller[6116]: Environment:        amd64, 1 processors, 448 MiB memory reserved for allocations
Apr 30 08:57:30 node1 Controller[6116]: System components initialization in progress
Apr 30 08:57:31 node1 Controller[6116]: 08:57:31.329 [main] INFO  LINSTOR/Controller - SYSTEM - ErrorReporter DB version 1 found.
Apr 30 08:57:31 node1 Controller[6116]: 08:57:31.331 [main] INFO  LINSTOR/Controller - SYSTEM - Log directory set to: '/var/log/linstor-controller'
Apr 30 08:57:31 node1 Controller[6116]: 08:57:31.402 [main] WARN  io.sentry.dsn.Dsn - *** Couldn't find a suitable DSN, Sentry operations will do nothing! See documentation: https://docs.sentry.io/clients/java/ ***
Apr 30 08:57:31 node1 Controller[6116]: 08:57:31.423 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading API classes started.
Apr 30 08:57:32 node1 Controller[6116]: 08:57:32.083 [Main] INFO  LINSTOR/Controller - SYSTEM - API classes loading finished: 660ms
Apr 30 08:57:32 node1 Controller[6116]: 08:57:32.084 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection started.
Apr 30 08:57:32 node1 Controller[6116]: 08:57:32.106 [Main] INFO  LINSTOR/Controller - SYSTEM - Attempting dynamic load of extension module "com.linbit.linstor.spacetracking.ControllerSpaceTrackingModule"
Apr 30 08:57:32 node1 Controller[6116]: 08:57:32.109 [Main] INFO  LINSTOR/Controller - SYSTEM - Extension module "com.linbit.linstor.spacetracking.ControllerSpaceTrackingModule" is not installed
Apr 30 08:57:32 node1 Controller[6116]: WARNING: An illegal reflective access operation has occurred
Apr 30 08:57:32 node1 Controller[6116]: WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/linstor-server/lib/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
Apr 30 08:57:32 node1 Controller[6116]: WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
Apr 30 08:57:32 node1 Controller[6116]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Apr 30 08:57:32 node1 Controller[6116]: WARNING: All illegal access operations will be denied in a future release
Apr 30 08:57:34 node1 Controller[6116]: 08:57:34.478 [Main] INFO  LINSTOR/Controller - SYSTEM - Dependency injection finished: 2393ms
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.056 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing authentication subsystem
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.266 [Main] INFO  LINSTOR/Controller - SYSTEM - Starting service instance 'TimerEventService' of type TimerEventService
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.267 [Main] INFO  LINSTOR/Controller - SYSTEM - Initializing the database connection pool
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.466 [Main] WARN  org.flywaydb.core.api.Location - Use of dots (.) as path separators will be deprecated in Flyway 7. Path: com.linbit.linstor.dbcp.migration
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.473 [Main] INFO  org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 6.5.7 by Redgate
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.549 [Main] INFO  org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:h2:/var/lib/linstor/linstordb (H2 1.4)
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.711 [Main] INFO  org.flywaydb.core.internal.command.DbValidate - Successfully validated 55 migrations (execution time 00:00.110s)
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.810 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Current version of schema "LINSTOR": 2021.04.12.12.00
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.810 [Main] WARN  org.flywaydb.core.internal.command.DbMigrate - outOfOrder mode is active. Migration of schema "LINSTOR" may not be reproducible.
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.812 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2021.04.29.12.00 - Fix duplicated restored layer data
Apr 30 08:57:35 node1 Controller[6116]: 08:57:35.974 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Migrating schema "LINSTOR" to version 2021.04.29.13.00 - Fix incorrectly written data after migration 2021.03.30.12.00
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.095 [Main] INFO  org.flywaydb.core.internal.command.DbMigrate - Successfully applied 2 migrations to schema "LINSTOR" (execution time 00:00.364s)
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.102 [Main] INFO  LINSTOR/Controller - SYSTEM - Starting service instance 'DatabaseService' of type DatabaseService
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.108 [Main] INFO  LINSTOR/Controller - SYSTEM - Loading security objects
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.140 [Main] INFO  LINSTOR/Controller - SYSTEM - Current security level is NO_SECURITY
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.173 [Main] INFO  LINSTOR/Controller - SYSTEM - Core objects load from database is in progress
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.308 [Main] ERROR LINSTOR/Controller - SYSTEM - Unknown error during loading data from DB [Report number 608BC67A-00000-000000]
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.320 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Shutdown in progress
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.323 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TaskScheduleService' of type TaskScheduleService
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.326 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TaskScheduleService' to complete shutdown
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.326 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'DatabaseService' of type DatabaseService
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.334 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'DatabaseService' to complete shutdown
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.334 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Shutting down service instance 'TimerEventService' of type TimerEventService
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.334 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Waiting for service instance 'TimerEventService' to complete shutdown
Apr 30 08:57:36 node1 Controller[6116]: 08:57:36.334 [Thread-2] INFO  LINSTOR/Controller - SYSTEM - Shutdown complete
Apr 30 08:57:36 node1 systemd[1]: linstor-controller.service: Main process exited, code=exited, status=199/n/a
Apr 30 08:57:36 node1 systemd[1]: linstor-controller.service: Failed with result 'exit-code'.
```

Here is the error report:

```
root@node1:~# linstor error-reports show 608BC67A-00000-000000
Error: Unable to connect to linstor://localhost:3370: [Errno 111] Connection refused
root@node1:~# ls -l /var/log/linstor-controller/
total 132
-rw-r--r-- 1 root root 11436 Mar  3 15:17 ErrorReport-603FA7E1-00000-000000.log
-rw-r--r-- 1 root root  4516 Apr 27 17:28 ErrorReport-60882FCA-00000-000000.log
-rw-r--r-- 1 root root  6406 Apr 30 08:57 ErrorReport-608BC67A-00000-000000.log
-rw-r--r-- 1 root root 94208 Apr 30 08:57 error-report.mv.db
-rw-r--r-- 1 root root     0 Feb 12 22:26 linstor-Controller.log
-rw-r--r-- 1 root root  7071 Apr 27 15:38 log-archive-2021-02.tar.gz
root@node1:~# cat /var/log/linstor-controller/ErrorReport-608BC67A-00000-000000.log
ERROR REPORT 608BC67A-00000-000000

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Controller
Version:                            1.12.1
Build ID:                           24fcedd9cbebfad42c7a195692e93c68d3ab978b
Build time:                         2021-04-30T07:35:24+00:00
Error time:                         2021-04-30 08:57:36
Node:                               node1

============================================================

Reported error:
===============

Category:                           Error
Class name:                         ImplementationError
Class canonical name:               com.linbit.ImplementationError
Generated at:                       Method 'loadAll', Source file 'DatabaseLoader.java', Line #589

Error message:                      Unknown error during loading data from DB

Call backtrace:

    Method                                   Native Class:Line number
    loadAll                                  N      com.linbit.linstor.dbdrivers.DatabaseLoader:589
    loadCoreObjects                          N      com.linbit.linstor.core.DbDataInitializer:176
    initialize                               N      com.linbit.linstor.core.DbDataInitializer:108
    startSystemServices                      N      com.linbit.linstor.core.ApplicationLifecycleManager:87
    start                                    N      com.linbit.linstor.core.Controller:343
    main                                     N      com.linbit.linstor.core.Controller:564

Caused by:
==========

Description:
    Failed to deserialize json array. Table: RESOURCE_GROUPS, column: REPLICAS_ON_SAME

Category:                           LinStorException
Class name:                         DatabaseException
Class canonical name:               com.linbit.linstor.dbdrivers.DatabaseException
Generated at:                       Method 'getAsStringList', Source file 'AbsDatabaseDriver.java', Line #319

Error message:                      Failed to deserialize json array. Table: RESOURCE_GROUPS, column: REPLICAS_ON_SAME

Call backtrace:

    Method                                   Native Class:Line number
    getAsStringList                          N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver$RawParameters:319
    load                                     N      com.linbit.linstor.core.objects.ResourceGroupDbDriver:283
    load                                     N      com.linbit.linstor.core.objects.ResourceGroupDbDriver:58
    restoreData                              N      com.linbit.linstor.dbdrivers.sql.SQLEngine:345
    loadAll                                  N      com.linbit.linstor.dbdrivers.sql.SQLEngine:279
    loadAll                                  N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver:100
    loadAll                                  N      com.linbit.linstor.dbdrivers.DatabaseLoader:263
    loadCoreObjects                          N      com.linbit.linstor.core.DbDataInitializer:176
    initialize                               N      com.linbit.linstor.core.DbDataInitializer:108
    startSystemServices                      N      com.linbit.linstor.core.ApplicationLifecycleManager:87
    start                                    N      com.linbit.linstor.core.Controller:343
    main                                     N      com.linbit.linstor.core.Controller:564

Caused by:
==========

Category:                           Exception
Class name:                         JsonParseException
Class canonical name:               com.fasterxml.jackson.core.JsonParseException
Generated at:                       Method '_constructError', Source file 'JsonParser.java', Line #1851

Error message:                      Unexpected character ('b' (code 98)): Expected space separating root-level values
 at [Source: (String)"5b5d"; line: 1, column: 3]

Call backtrace:

    Method                                   Native Class:Line number
    _constructError                          N      com.fasterxml.jackson.core.JsonParser:1851
    _reportError                             N      com.fasterxml.jackson.core.base.ParserMinimalBase:707
    _reportUnexpectedChar                    N      com.fasterxml.jackson.core.base.ParserMinimalBase:632
    _reportMissingRootWS                     N      com.fasterxml.jackson.core.base.ParserMinimalBase:679
    _verifyRootSpace                         N      com.fasterxml.jackson.core.json.ReaderBasedJsonParser:1706
    _parsePosNumber                          N      com.fasterxml.jackson.core.json.ReaderBasedJsonParser:1349
    nextToken                                N      com.fasterxml.jackson.core.json.ReaderBasedJsonParser:773
    _initForReading                          N      com.fasterxml.jackson.databind.ObjectMapper:4664
    _readMapAndClose                         N      com.fasterxml.jackson.databind.ObjectMapper:4513
    readValue                                N      com.fasterxml.jackson.databind.ObjectMapper:3468
    readValue                                N      com.fasterxml.jackson.databind.ObjectMapper:3436
    getAsStringList                          N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver$RawParameters:300
    load                                     N      com.linbit.linstor.core.objects.ResourceGroupDbDriver:283
    load                                     N      com.linbit.linstor.core.objects.ResourceGroupDbDriver:58
    restoreData                              N      com.linbit.linstor.dbdrivers.sql.SQLEngine:345
    loadAll                                  N      com.linbit.linstor.dbdrivers.sql.SQLEngine:279
    loadAll                                  N      com.linbit.linstor.dbdrivers.AbsDatabaseDriver:100
    loadAll                                  N      com.linbit.linstor.dbdrivers.DatabaseLoader:263
    loadCoreObjects                          N      com.linbit.linstor.core.DbDataInitializer:176
    initialize                               N      com.linbit.linstor.core.DbDataInitializer:108
    startSystemServices                      N      com.linbit.linstor.core.ApplicationLifecycleManager:87
    start                                    N      com.linbit.linstor.core.Controller:343
    main                                     N      com.linbit.linstor.core.Controller:564


END OF ERROR REPORT.
root@node1:~#
```

**Comment by candlerb** [comment]
Aside: just prior to doing this upgrade, I had created the resources as shown [here](https://github.com/LINBIT/linstor-server/issues/222#issuecomment-829955502).

**Comment by candlerb** [comment]
Possibly also relevant:

```
root@node1:~# ls -l /var/lib/linstor/
total 1672
-rw-r--r-- 1 root root 372736 Apr 30 08:57 linstordb.mv.db
-rw-r--r-- 1 root root 626688 Apr 28 10:25 linstordb.mv.db-2021-04-28T10:25+00:00.bak
-rw-r--r-- 1 root root 352256 Apr 30 08:56 linstordb.mv.db-2021-04-30T08:56+00:00.bak
-rw-r--r-- 1 root root 352256 Apr 30 08:56 linstordb.mv.db.bak
-rw-r--r-- 1 root root   5700 Apr 27 17:28 linstordb.trace.db
-rw-r--r-- 1 root root      0 Apr 30 08:51 loop_device_mapping
```

There is an exception in `linstordb.trace.db` but it's from a few days ago, when I upgraded to 1.12.0, and I suspect is harmless (dropping a constraint which didn't exist in the first place)

```
root@node1:~# cat /var/lib/linstor/linstordb.trace.db
2021-02-12 22:26:17 jdbc[5]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK_LDRD_VD" not found; SQL statement:
ALTER TABLE LAYER_DRBD_VOLUME_DEFINITIONS DROP CONSTRAINT FK_LDRD_VD [90057-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:41)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:136)
	at com.linbit.linstor.dbdrivers.SQLUtils.executeStatement(SQLUtils.java:31)
	at com.linbit.linstor.dbdrivers.SQLUtils.runSql(SQLUtils.java:107)
	at com.linbit.linstor.dbcp.migration.Migration_2019_03_15_FixConstraints.attemptSql(Migration_2019_03_15_FixConstraints.java:169)
	at com.linbit.linstor.dbcp.migration.Migration_2019_03_15_FixConstraints.migrate(Migration_2019_03_15_FixConstraints.java:52)
	at com.linbit.linstor.dbcp.migration.LinstorMigration.migrate(LinstorMigration.java:66)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.executeOnce(JavaMigrationExecutor.java:64)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.access$000(JavaMigrationExecutor.java:35)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor$1.call(JavaMigrationExecutor.java:56)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor$1.call(JavaMigrationExecutor.java:53)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
	at org.flywaydb.core.internal.resolver.java.JavaMigrationExecutor.execute(JavaMigrationExecutor.java:53)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:366)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:206)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:158)
	at org.flywaydb.core.Flyway.execute(Flyway.java:527)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
	at com.linbit.linstor.dbcp.DbConnectionPool.migrate(DbConnectionPool.java:220)
	at com.linbit.linstor.dbcp.DbConnectionPoolInitializer.initialize(DbConnectionPoolInitializer.java:50)
	at com.linbit.linstor.core.ApplicationLifecycleManager.startSystemServices(ApplicationLifecycleManager.java:87)
	at com.linbit.linstor.core.Controller.start(Controller.java:337)
	at com.linbit.linstor.core.Controller.main(Controller.java:558)
2021-04-27 17:28:15 jdbc[7]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1526)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1502)
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:455)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at org.apache.commons.dbcp2.DelegatingConnection.setAutoCommit(DelegatingConnection.java:537)
	at com.linbit.linstor.dbcp.DbConnectionPool.getConnection(DbConnectionPool.java:162)
	at com.linbit.linstor.transaction.manager.ControllerSQLTransactionMgr.<init>(ControllerSQLTransactionMgr.java:20)
	at com.linbit.linstor.transaction.manager.ControllerSQLTransactionMgrGenerator.startTransaction(ControllerSQLTransactionMgrGenerator.java:28)
	at com.linbit.linstor.tasks.ReconnectorTask.run(ReconnectorTask.java:283)
	at com.linbit.linstor.tasks.TaskScheduleService.execute(TaskScheduleService.java:282)
	at com.linbit.linstor.tasks.TaskScheduleService.run(TaskScheduleService.java:228)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by candlerb** [comment]
```
root@node1:~# strings /var/lib/linstor/linstordb.mv.db | grep 5b5d
5b5d
5b5dF[]
5b5d
5b5dF[]
5b5d
5b5dF[]
5b5d
5b5dF[]
root@node1:~# strings /var/lib/linstor/linstordb.mv.db | less
root@node1:~# strings /var/lib/linstor/linstordb.mv.db | grep -3 5b5d
[]F[]
$6051656e-690f-463d-a3f0-cc858158548aLSSD_CRITLssd_critDF[]#
["pool_ssd"]
5b5d
5b5dF[]
NDFLTRSCGRP1
PMY_SSD_GROUP2
LSSD_CRIT3
--
[]F[]
$6051656e-690f-463d-a3f0-cc858158548aLSSD_CRITLssd_critDF[]#
["pool_ssd"]
5b5d
5b5dF[]
$9c30059a-8b18-4334-b5c8-62fcf9c1bf7dKSSD_STDKssd_stdDF[]"
["pool_ssd"]
5b5d
5b5dF[]
NDFLTRSCGRP1
PMY_SSD_GROUP2
LSSD_CRIT3
--
4fc0002ca340
09c30059a-8b18-4334-b5c8-62fcf9c1bf7dKSSD_STDKssd_stdDF[]"
["pool_ssd"]
5b5d
5b5dF[]
NDFLTRSCGRP1
PMY_SSD_GROUP2
LSSD_CRIT3
```

**Comment by rp-** [comment]
It sadly seems our migration-script didn't work for resource-groups created in v1.12.0 (prior versions not affected).
So we will probably have to come up with a better migration script for that.

You should be able to fix it yourself with the following:
`echo "UPDATE LINSTOR.RESOURCE_GROUPS SET REPLICAS_ON_SAME='[]', REPLICAS_ON_DIFFERENT='[]' WHERE RESOURCE_GROUP_NAME IN ('SSD_CRIT', 'SSD_STD');" | /usr/share/linstor-server/bin/linstor-config sql-script /etc/linstor/linstor.toml`

**Comment by candlerb** [comment]
That does indeed fix the problem on my system (which is just a test environment BTW)

I'll close this now.  You can decide whether the short window between 1.12.0 and 1.12.1 warrants any further work or just a release note.

Thanks for your quick response!
