### ISSUE TITLE
Unable to start grizzly http server

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#292]
Hi, I just faced with some problem.

Linstor-controller is started but does not serve any requests. In the log of linstor-controller:

```
06:21:43.195 [Main] ERROR LINSTOR/Controller - SYSTEM - Unable to start grizzly http server on 127.0.0.1:3370.
```

Enabling trace logging does not provides any additional information. ErrorReports are missing.
Any ideas how to diagnose this? 

- **LINSTOR version:** v1.18.2
- **OS:** Astra Linux 1.7

Configs:
```yaml
  linstor-client.conf: |+
    [global]
    controllers = https://linstor.d8-linstor.svc:3371
    cafile      = /etc/linstor/client/ca.crt
    certfile    = /etc/linstor/client/tls.crt
    keyfile     = /etc/linstor/client/tls.key

  linstor.toml: |
    [http]
      listen_addr = "127.0.0.1"

    [https]
      enabled = true
      keystore = "/etc/linstor/https/keystore.jks"
      keystore_password = "linstor"
      truststore = "/etc/linstor/https/truststore.jks"
      truststore_password = "linstor"

    [db]
      connection_url = "k8s"

    [logging]
      linstor_level = "TRACE"
```

ss shows that linstor is listening tcp port:

![image](https://user-images.githubusercontent.com/7556217/174065942-814e9faf-352e-45bc-9b7b-a03eb52c0a6e.png)

ref: https://github.com/deckhouse/deckhouse/issues/1804

**Comment by rp-** [comment]
You could print the sockeexception somehwere here:
https://github.com/LINBIT/linstor-server/blob/master/controller/src/main/java/com/linbit/linstor/api/rest/v1/config/GrizzlyHttpService.java#L323

But usually you would get something like that if the port is blocked or no permission to open a port...
Not much linstor can do about.

**Comment by kvaps** [comment]
@rp- thanks for pointing out, here is what I found:
```
12:47:52.406 [Main] ERROR LINSTOR/Controller - SYSTEM - Unable to start grizzly http server on 127.0.0.1:3370.
java.net.SocketException: Protocol family unavailable
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bindToChannelAndAddress(TCPNIOBindingHandler.java:107)
        at org.glassfish.grizzly.nio.transport.TCPNIOBindingHandler.bind(TCPNIOBindingHandler.java:64)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:215)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:195)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.bind(TCPNIOTransport.java:186)
        at org.glassfish.grizzly.http.server.NetworkListener.start(NetworkListener.java:711)
        at org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:256)
        at com.linbit.linstor.api.rest.v1.config.GrizzlyHttpService.start(GrizzlyHttpService.java:318)
        at com.linbit.linstor.systemstarter.GrizzlyInitializer.initialize(GrizzlyInitializer.java:88)
        at com.linbit.linstor.core.ApplicationLifecycleManager.startSystemServices(ApplicationLifecycleManager.java:87)
        at com.linbit.linstor.core.Controller.start(Controller.java:347)
        at com.linbit.linstor.core.Controller.main(Controller.java:586)
```


It seems that linstor-server can't work while IPv6 support is not enabled in kernel.

User is switched it down via kernel parameters:
```ini
GRUB_CMDLINE_LINUX="ipv6.disable=1"
```

**Comment by rp-** [comment]
I guess the easiest solution here is, to just provide an ipv4 `listen_addr` in the https section, as we try to bind to ipv6 per default.

**Comment by rp-** [comment]
I'll improve the error logging, as the error is a bit misleading and the exception (as we see) might be helpful
