### ISSUE TITLE
Error when run "linstor node list" linstor-server 0.7.1

### ISSUE THREAD

**Issue by jonatasvieira** [LINBIT/linstor-server#33]
I'm getting the following error when i try to list my nodes on linstor.

**Traceback (most recent call last):
  File "/usr/bin/linstor", line 21, in <module>
    import linstor_client_main
  File "/usr/lib/python3.4/site-packages/linstor_client-0.7.0-py3.4.egg/linstor_client_main.py", line 30, in <module>
    import linstor
  File "/usr/lib/python3.4/site-packages/python_linstor-0.7.0-py3.4.egg/linstor/__init__.py", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/python_linstor-0.7.0-py3.4.egg/linstor/linstorapi.py", line 23, in <module>
ImportError: No module named 'linstor.proto.MsgHeader_pb2'**

When i downloaded linstor-server, my big question was "what to do with these java files?".
Reading makefile and build.gradle, i downloaded protoc, running:
make getprotoc 

then i run:
make genJava
gradle assemble 
make copytolibs

Every command on root of linstor-server.

**Comment by rp-** [comment]
How did you install the client?

**Comment by rp-** [comment]
oh, that is not really used by us (so not really tested)
you will definitely want to do
`make gensrc` in the linstor-api-py before doing `make install`
