### ISSUE TITLE
ETCD: crash on export-db after import-db

### ISSUE THREAD

**Issue by ggzengel** [LINBIT/linstor-server#365]
I migrated successfully from H2 to ETCD.
For backup I tried export-db and got this error:

```
$/usr/share/linstor-server/bin/linstor-database export-db -c /etc/linstor/ test
Loading configuration file "/etc/linstor/linstor.toml"
15:25:01.547 [main] INFO LINSTOR/linstor-db -- SYSTEM - ErrorReporter DB version 1 found.
15:25:01.549 [main] INFO LINSTOR/linstor-db -- SYSTEM - Log directory set to: './logs'
15:25:01.970 [main] INFO LINSTOR/linstor-db -- SYSTEM - Attempting dynamic load of extension module "com.linbit.linstor.modularcrypto.FipsCryptoModule"
15:25:01.970 [main] INFO LINSTOR/linstor-db -- SYSTEM - Extension module "com.linbit.linstor.modularcrypto.FipsCryptoModule" is not installed
15:25:01.971 [main] INFO LINSTOR/linstor-db -- SYSTEM - Attempting dynamic load of extension module "com.linbit.linstor.modularcrypto.JclCryptoModule"
15:25:01.983 [main] INFO LINSTOR/linstor-db -- SYSTEM - Dynamic load of extension module "com.linbit.linstor.modularcrypto.JclCryptoModule" was successful
15:25:01.983 [main] INFO LINSTOR/linstor-db -- SYSTEM - Attempting dynamic load of extension module "com.linbit.linstor.spacetracking.ControllerSpaceTrackingModule"
15:25:01.984 [main] INFO LINSTOR/linstor-db -- SYSTEM - Dynamic load of extension module "com.linbit.linstor.spacetracking.ControllerSpaceTrackingModule" was successful
15:25:02.844 [main] INFO LINSTOR/linstor-db -- SYSTEM - Initializing the etcd database
15:25:02.844 [main] INFO LINSTOR/linstor-db -- SYSTEM - etcd connection URL is "etcd://px1:2379,px2:2379,px3:2379,px4:2379"
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.linbit.linstor.core.LinstorDatabaseTool$CmdExportDb@66a3ffec): com.linbit.linstor.core.apicallhandler.response.ApiRcException: Unknown exception occured
	at picocli.CommandLine.executeUserObject(CommandLine.java:2050)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:2264)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:2664)
	at picocli.CommandLine.parseWithHandler(CommandLine.java:2599)
	at com.linbit.linstor.core.LinstorDatabaseTool.main(LinstorDatabaseTool.java:241)
Caused by: com.linbit.linstor.core.apicallhandler.response.ApiRcException: Unknown exception occured
	at com.linbit.linstor.core.apicallhandler.controller.db.DbExportImportHelper.export(DbExportImportHelper.java:206)
	at com.linbit.linstor.core.LinstorDatabaseTool$CmdExportDb.lambda$call$0(LinstorDatabaseTool.java:105)
	at com.linbit.linstor.core.LinstorDatabaseTool.runDbExportImport(LinstorDatabaseTool.java:233)
	at com.linbit.linstor.core.LinstorDatabaseTool$CmdExportDb.call(LinstorDatabaseTool.java:101)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	... 8 more
Caused by: java.lang.NumberFormatException: For input string: "Fri Aug 04 00"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.linbit.linstor.dbdrivers.RawParameters.getValueFromEtcd(RawParameters.java:121)
	at com.linbit.linstor.dbdrivers.RawParameters.getParsed(RawParameters.java:54)
	at com.linbit.linstor.dbdrivers.k8s.crd.GenCrdCurrent$SpaceHistorySpec.fromRawParameters(GenCrdCurrent.java:8297)
	at com.linbit.linstor.dbdrivers.k8s.crd.GenCrdCurrent.rawParamToSpec(GenCrdCurrent.java:544)
	at com.linbit.linstor.dbdrivers.AbsDatabaseDriver.export(AbsDatabaseDriver.java:94)
	at com.linbit.linstor.core.apicallhandler.controller.db.DbExportImportHelper.export(DbExportImportHelper.java:187)
	... 12 more
```

I use:

```
# apt list | grep linstor

linstor-client/unknown,now 1.19.0-1 all [installed]
linstor-common/unknown,now 1.24.0-1 all [installed,automatic]
linstor-controller/unknown,now 1.24.0-1 all [installed]
linstor-proxmox/unknown,now 7.0.1-1 all [installed]
linstor-satellite/unknown,now 1.24.0-1 all [installed]
python-linstor/unknown,now 1.19.0-1 all [installed,automatic]

# lsb_release -a

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

**Comment by ggzengel** [comment]
After deleting /LINSTOR/SPACE_HISTORY it shows an exception on:
>/LINSTOR/TRACKING_DATE/ENTRY_DATE
Mon Aug 07 00:00:00 UTC 2023

**Comment by ghernadi** [comment]
Thanks for the report. Would you mind sending me a DB dump of the original ETCD (i.e. before you deleted those entries)? I can try to write a migration that converts those dates to the expected format.

**Comment by ggzengel** [comment]
fixed
