### ISSUE TITLE
'QuerySpaceTracking' Exception

### ISSUE THREAD

**Issue by youzuoyong** [LINBIT/linstor-server#413]
2024_07_04 04:10:47.761 [MainWorkerPool-1] DEBUG LINSTOR/Satellite - SYSTEM - Peer 10.190.17.134:39282, API call 18 'QuerySpaceTracking' start (seq 15)
2024_07_04 04:10:47.762 [MainWorkerPool-1] WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoSuchMethodError: 'java.util.Map com.linbit.linstor.core.apicallhandler.StltApiCallHandlerUtils.getSpaceInfo(boolean)'
	at com.linbit.linstor.api.protobuf.QuerySpaceTracking.a(QuerySpaceTracking.java:186)
	at com.linbit.linstor.api.protobuf.QuerySpaceTracking.a(QuerySpaceTracking.java:136)
	at com.linbit.linstor.api.protobuf.QuerySpaceTracking.b(QuerySpaceTracking.java:103)
	at com.linbit.linstor.core.apicallhandler.ScopeRunner.doInScope(ScopeRunner.java:149)
	at com.linbit.linstor.core.apicallhandler.ScopeRunner.lambda$fluxInScope$0(ScopeRunner.java:76)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:127)
	at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8759)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribe(MonoFlatMapMany.java:141)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8773)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
	at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8759)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427)
	at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:127)
	at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371)
	at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:70)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8773)
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:258)
	at reactor.core.publisher.FluxConcatArray.subscribe(FluxConcatArray.java:78)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.Flux.subscribe(Flux.java:8773)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:453)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:724)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:256)
	at reactor.core.publisher.SinkManyUnicast.drainFused(SinkManyUnicast.java:319)
	at reactor.core.publisher.SinkManyUnicast.drain(SinkManyUnicast.java:362)
	at reactor.core.publisher.SinkManyUnicast.tryEmitNext(SinkManyUnicast.java:237)
	at reactor.core.publisher.SinkManySerialized.tryEmitNext(SinkManySerialized.java:100)
	at com.linbit.linstor.netcom.TcpConnectorPeer.processInOrder(TcpConnectorPeer.java:392)
	at com.linbit.linstor.proto.CommonMessageProcessor.doProcessMessage(CommonMessageProcessor.java:227)
	at com.linbit.linstor.proto.CommonMessageProcessor.lambda$processMessage$2(CommonMessageProcessor.java:164)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ghernadi** [comment]
My guess would be that you are trying to use a new version of LINSTOR with an old version of the SpaceTracking feature. Those two are defined in different .jar files. Where did you get your SpaceTracking jar file from?

**Comment by youzuoyong** [comment]
OK, thanks.
