### ISSUE TITLE
Can not change listen/bind address.

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#5]
```
# /usr/share/linstor-server/bin/linstor-config set-plain-listen /var/lib/linstor/linstordb.mv.db 127.0.0.1
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.linbit.linstor.core.LinstorConfig$CmdSetPlainListen@1c4af82c): java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at picocli.CommandLine.execute(CommandLine.java:544)
        at picocli.CommandLine.access$600(CommandLine.java:143)
        at picocli.CommandLine$RunLast.handleParseResult(CommandLine.java:624)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:742)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:695)
        at com.linbit.linstor.core.LinstorConfig.main(LinstorConfig.java:158)
Caused by: java.util.InvalidPropertiesFormatException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:80)
        at java.util.Properties$XmlSupport.load(Properties.java:1201)
        at java.util.Properties.loadFromXML(Properties.java:881)
        at com.linbit.linstor.core.LinstorConfig.initConnectionProviderFromCfg(LinstorConfig.java:192)
        at com.linbit.linstor.core.LinstorConfig.access$200(LinstorConfig.java:26)
        at com.linbit.linstor.core.LinstorConfig$CmdSetPlainListen.call(LinstorConfig.java:141)
        at picocli.CommandLine.execute(CommandLine.java:542)
        ... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:994)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at sun.util.xml.PlatformXmlPropertiesProvider.getLoadingDoc(PlatformXmlPropertiesProvider.java:106)
        at sun.util.xml.PlatformXmlPropertiesProvider.load(PlatformXmlPropertiesProvider.java:78)
        ... 11 more
```

**Comment by raltnoeder** [comment]
Thanks for the report. I have scheduled this problem for analysis.

**Comment by rp-** [comment]
Usage is wrong here, the 1. positional argument should be the `database.cfg` file, which should be per default in `/etc/linstor/database.cfg`

**Comment by kvaps** [comment]
@rp- , please reopen iisue

there is still the problem:

```
# /usr/share/linstor-server/bin/linstor-config set-plain-listen /etc/linstor/database.cfg 127.0.0.1
Error: UPDATE PROPS_CONTAINERS SET PROP_VALUE='127.0.0.1' WHERE PROPS_INSTANCE='CTRLCFG' AND PROP_KEY='netcom/PlainConnector/bindaddress'
Exception in thread "main" picocli.CommandLine$ExecutionException: Error while calling command (com.linbit.linstor.core.LinstorConfig$CmdSetPlainListen@553a3d88): org.h2.jdbc.JdbcSQLException: Table "PROPS_CONTAINERS" not found; SQL statement:
UPDATE PROPS_CONTAINERS SET PROP_VALUE='127.0.0.1' WHERE PROPS_INSTANCE='CTRLCFG' AND PROP_KEY='netcom/PlainConnector/bindaddress' [42102-197]
        at picocli.CommandLine.execute(CommandLine.java:544)
        at picocli.CommandLine.access$600(CommandLine.java:143)
        at picocli.CommandLine$RunLast.handleParseResult(CommandLine.java:624)
        at picocli.CommandLine.parseWithHandlers(CommandLine.java:742)
        at picocli.CommandLine.parseWithHandler(CommandLine.java:695)
        at com.linbit.linstor.core.LinstorConfig.main(LinstorConfig.java:158)
Caused by: org.h2.jdbc.JdbcSQLException: Table "PROPS_CONTAINERS" not found; SQL statement:
UPDATE PROPS_CONTAINERS SET PROP_VALUE='127.0.0.1' WHERE PROPS_INSTANCE='CTRLCFG' AND PROP_KEY='netcom/PlainConnector/bindaddress' [42102-197]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.command.Parser.readTableOrView(Parser.java:5920)
        at org.h2.command.Parser.readTableOrView(Parser.java:5897)
        at org.h2.command.Parser.readSimpleTableFilter(Parser.java:838)
        at org.h2.command.Parser.parseUpdate(Parser.java:778)
        at org.h2.command.Parser.parsePrepared(Parser.java:485)
        at org.h2.command.Parser.parse(Parser.java:335)
        at org.h2.command.Parser.parse(Parser.java:307)
        at org.h2.command.Parser.prepareCommand(Parser.java:278)
        at org.h2.engine.Session.prepareLocal(Session.java:611)
        at org.h2.engine.Session.prepareCommand(Session.java:549)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:291)
        at org.apache.commons.dbcp2.DelegatingConnection.prepareStatement(DelegatingConnection.java:291)
        at com.linbit.linstor.dbdrivers.GenericDbDriver.executeStatement(GenericDbDriver.java:462)
        at com.linbit.linstor.core.LinstorConfig$CmdSetPlainListen.call(LinstorConfig.java:146)
        at picocli.CommandLine.execute(CommandLine.java:542)
        ... 5 more
```

**Comment by rp-** [comment]
I guess this is because the database was not created yet.
linstor-controller has to run at least 1 time to create the database.
We might add a controller start mode, that just handles database init and migration from older versions.

**Comment by kvaps** [comment]
No, it's after, it is already working database,
I'm forced to use a firewall to get around this

**Comment by rp-** [comment]
Ok, that bug was weird, it worked on 2 out of 3 systems here.
But I found the cause and fixed it, will be in the next release.

For now if you want to change the listen address you can save this snippet in a file and feed it to linstor-config.
`UPDATE LINSTOR.PROPS_CONTAINERS SET PROP_VALUE='127.0.0.1' WHERE PROPS_INSTANCE='CTRLCFG' AND PROP_KEY='netcom/PlainConnector/bindaddress'`

save this to a file and run linstor-config like this:
`linstor-config sql-script /etc/linstor/database.cfg savedscript.sql`

**Comment by raltnoeder** [comment]
As a temporary fix, you can start the Controller with the local interactive debug console and enter the following commands:
```
setcfgval namespace(netcom) key(PlainConnector/bindaddress) value(127.0.0.1)
shtdwn
```
Then restart the Controller as usual.

**Comment by kvaps** [comment]
working, thanks!
