### ISSUE TITLE
Curl command for list-properties (IndexError: list index out of range)

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-server#63]
```
# linstor --curl controller list-properties
curl -X GET http://localhost:3370/v1/controller/properties
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 627, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 592, in run
    rc = self.parse_and_execute(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 307, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/controller_cmds.py", line 77, in cmd_print_controller_props
    return self.output_props_list(args, lstmsg, self._props_list)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 301, in output_props_list
    lstmsg = lstmsg[0]
IndexError: list index out of range
```

```
# linstor --curl n lp m1c4
curl -X GET http://localhost:3370/v1/nodes
Traceback (most recent call last):
  File "/usr/bin/linstor", line 24, in <module>
    linstor_client_main.main()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 627, in main
    LinStorCLI().run()
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 592, in run
    rc = self.parse_and_execute(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/linstor_client_main.py", line 307, in parse_and_execute
    rc = args.func(args)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/node_cmds.py", line 610, in print_props
    return self.output_props_list(args, lstmsg, self._props_list)
  File "/usr/lib/python2.7/dist-packages/linstor_client/commands/commands.py", line 301, in output_props_list
    lstmsg = lstmsg[0]
IndexError: list index out of range
```

```
# linstor --version
linstor 0.9.6; GIT-hash: c7c973dc39c93e8d45d2b7e3a0907b1d20fb3dfe
```

**Comment by kvaps** [comment]
fixed after upgrade to 0.9.8
